//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSDGAPI.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gateway.mobile.eseva.com", ConfigurationName="ServiceReference1.TsmobileapssPortType")]
    public interface TsmobileapssPortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:HmwssbBillDetails", ReplyAction="urn:HmwssbBillDetailsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MSDGAPI.ServiceReference1.HmwssbBillDetailsResponse HmwssbBillDetails(MSDGAPI.ServiceReference1.HmwssbBillDetailsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:AirtelBillDetails", ReplyAction="urn:AirtelBillDetailsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MSDGAPI.ServiceReference1.AirtelBillDetailsResponse AirtelBillDetails(MSDGAPI.ServiceReference1.AirtelBillDetailsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:IdeaBillDetails", ReplyAction="urn:IdeaBillDetailsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MSDGAPI.ServiceReference1.IdeaBillDetailsResponse IdeaBillDetails(MSDGAPI.ServiceReference1.IdeaBillDetailsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:AirtelLandLineBillDetails", ReplyAction="urn:AirtelLandLineBillDetailsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MSDGAPI.ServiceReference1.AirtelLandLineBillDetailsResponse AirtelLandLineBillDetails(MSDGAPI.ServiceReference1.AirtelLandLineBillDetailsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auth.gateway.mobile.eseva.com/xsd")]
    public partial class AuthRequestBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string groupidField;
        
        private string passwordField;
        
        private string serviceidField;
        
        private string strCentrecodeField;
        
        private string strDistcodeField;
        
        private string strStaffcodeField;
        
        private string strdeptcodeField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string groupid {
            get {
                return this.groupidField;
            }
            set {
                this.groupidField = value;
                this.RaisePropertyChanged("groupid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string serviceid {
            get {
                return this.serviceidField;
            }
            set {
                this.serviceidField = value;
                this.RaisePropertyChanged("serviceid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string strCentrecode {
            get {
                return this.strCentrecodeField;
            }
            set {
                this.strCentrecodeField = value;
                this.RaisePropertyChanged("strCentrecode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string strDistcode {
            get {
                return this.strDistcodeField;
            }
            set {
                this.strDistcodeField = value;
                this.RaisePropertyChanged("strDistcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string strStaffcode {
            get {
                return this.strStaffcodeField;
            }
            set {
                this.strStaffcodeField = value;
                this.RaisePropertyChanged("strStaffcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string strdeptcode {
            get {
                return this.strdeptcodeField;
            }
            set {
                this.strdeptcodeField = value;
                this.RaisePropertyChanged("strdeptcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://airtelLandLine.gateway.mobile.eseva.com/xsd")]
    public partial class AirtelLandLineBillResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strAccountnoField;
        
        private string strBillamountField;
        
        private string strConsumernameField;
        
        private string strReqidField;
        
        private string strResCodeField;
        
        private string strResDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string strAccountno {
            get {
                return this.strAccountnoField;
            }
            set {
                this.strAccountnoField = value;
                this.RaisePropertyChanged("strAccountno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string strBillamount {
            get {
                return this.strBillamountField;
            }
            set {
                this.strBillamountField = value;
                this.RaisePropertyChanged("strBillamount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string strConsumername {
            get {
                return this.strConsumernameField;
            }
            set {
                this.strConsumernameField = value;
                this.RaisePropertyChanged("strConsumername");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string strReqid {
            get {
                return this.strReqidField;
            }
            set {
                this.strReqidField = value;
                this.RaisePropertyChanged("strReqid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string strResCode {
            get {
                return this.strResCodeField;
            }
            set {
                this.strResCodeField = value;
                this.RaisePropertyChanged("strResCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string strResDesc {
            get {
                return this.strResDescField;
            }
            set {
                this.strResDescField = value;
                this.RaisePropertyChanged("strResDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://idea.gateway.mobile.eseva.com/xsd")]
    public partial class IdeaBillResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strAccountnoField;
        
        private string strAdd1Field;
        
        private string strAdd2Field;
        
        private string strAdd3Field;
        
        private string strBillamountField;
        
        private string strConsumernameField;
        
        private string strReqidField;
        
        private string strResCodeField;
        
        private string strResDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string strAccountno {
            get {
                return this.strAccountnoField;
            }
            set {
                this.strAccountnoField = value;
                this.RaisePropertyChanged("strAccountno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string strAdd1 {
            get {
                return this.strAdd1Field;
            }
            set {
                this.strAdd1Field = value;
                this.RaisePropertyChanged("strAdd1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string strAdd2 {
            get {
                return this.strAdd2Field;
            }
            set {
                this.strAdd2Field = value;
                this.RaisePropertyChanged("strAdd2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string strAdd3 {
            get {
                return this.strAdd3Field;
            }
            set {
                this.strAdd3Field = value;
                this.RaisePropertyChanged("strAdd3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string strBillamount {
            get {
                return this.strBillamountField;
            }
            set {
                this.strBillamountField = value;
                this.RaisePropertyChanged("strBillamount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string strConsumername {
            get {
                return this.strConsumernameField;
            }
            set {
                this.strConsumernameField = value;
                this.RaisePropertyChanged("strConsumername");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string strReqid {
            get {
                return this.strReqidField;
            }
            set {
                this.strReqidField = value;
                this.RaisePropertyChanged("strReqid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string strResCode {
            get {
                return this.strResCodeField;
            }
            set {
                this.strResCodeField = value;
                this.RaisePropertyChanged("strResCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string strResDesc {
            get {
                return this.strResDescField;
            }
            set {
                this.strResDescField = value;
                this.RaisePropertyChanged("strResDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://airtel.gateway.mobile.eseva.com/xsd")]
    public partial class AirtelBillResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strAccountnoField;
        
        private string strBillamountField;
        
        private string strConsumernameField;
        
        private string strReqidField;
        
        private string strResCodeField;
        
        private string strResDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string strAccountno {
            get {
                return this.strAccountnoField;
            }
            set {
                this.strAccountnoField = value;
                this.RaisePropertyChanged("strAccountno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string strBillamount {
            get {
                return this.strBillamountField;
            }
            set {
                this.strBillamountField = value;
                this.RaisePropertyChanged("strBillamount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string strConsumername {
            get {
                return this.strConsumernameField;
            }
            set {
                this.strConsumernameField = value;
                this.RaisePropertyChanged("strConsumername");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string strReqid {
            get {
                return this.strReqidField;
            }
            set {
                this.strReqidField = value;
                this.RaisePropertyChanged("strReqid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string strResCode {
            get {
                return this.strResCodeField;
            }
            set {
                this.strResCodeField = value;
                this.RaisePropertyChanged("strResCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string strResDesc {
            get {
                return this.strResDescField;
            }
            set {
                this.strResDescField = value;
                this.RaisePropertyChanged("strResDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hmwssb.gateway.mobile.eseva.com/xsd")]
    public partial class HmwssbBillResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strAddressField;
        
        private string strAmountField;
        
        private string strCanField;
        
        private string strCategoryField;
        
        private string strEmailField;
        
        private string strMobilenoField;
        
        private string strNameField;
        
        private string strReqIdField;
        
        private string strResCodeField;
        
        private string strResDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string strAddress {
            get {
                return this.strAddressField;
            }
            set {
                this.strAddressField = value;
                this.RaisePropertyChanged("strAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string strAmount {
            get {
                return this.strAmountField;
            }
            set {
                this.strAmountField = value;
                this.RaisePropertyChanged("strAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string strCan {
            get {
                return this.strCanField;
            }
            set {
                this.strCanField = value;
                this.RaisePropertyChanged("strCan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string strCategory {
            get {
                return this.strCategoryField;
            }
            set {
                this.strCategoryField = value;
                this.RaisePropertyChanged("strCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string strEmail {
            get {
                return this.strEmailField;
            }
            set {
                this.strEmailField = value;
                this.RaisePropertyChanged("strEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string strMobileno {
            get {
                return this.strMobilenoField;
            }
            set {
                this.strMobilenoField = value;
                this.RaisePropertyChanged("strMobileno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string strName {
            get {
                return this.strNameField;
            }
            set {
                this.strNameField = value;
                this.RaisePropertyChanged("strName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string strReqId {
            get {
                return this.strReqIdField;
            }
            set {
                this.strReqIdField = value;
                this.RaisePropertyChanged("strReqId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string strResCode {
            get {
                return this.strResCodeField;
            }
            set {
                this.strResCodeField = value;
                this.RaisePropertyChanged("strResCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string strResDesc {
            get {
                return this.strResDescField;
            }
            set {
                this.strResDescField = value;
                this.RaisePropertyChanged("strResDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HmwssbBillDetails", WrapperNamespace="http://gateway.mobile.eseva.com", IsWrapped=true)]
    public partial class HmwssbBillDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gateway.mobile.eseva.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string strConsno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gateway.mobile.eseva.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MSDGAPI.ServiceReference1.AuthRequestBean RequestBean;
        
        public HmwssbBillDetailsRequest() {
        }
        
        public HmwssbBillDetailsRequest(string strConsno, MSDGAPI.ServiceReference1.AuthRequestBean RequestBean) {
            this.strConsno = strConsno;
            this.RequestBean = RequestBean;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HmwssbBillDetailsResponse", WrapperNamespace="http://gateway.mobile.eseva.com", IsWrapped=true)]
    public partial class HmwssbBillDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gateway.mobile.eseva.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MSDGAPI.ServiceReference1.HmwssbBillResponse @return;
        
        public HmwssbBillDetailsResponse() {
        }
        
        public HmwssbBillDetailsResponse(MSDGAPI.ServiceReference1.HmwssbBillResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AirtelBillDetails", WrapperNamespace="http://gateway.mobile.eseva.com", IsWrapped=true)]
    public partial class AirtelBillDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gateway.mobile.eseva.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string strMobileno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gateway.mobile.eseva.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MSDGAPI.ServiceReference1.AuthRequestBean RequestBean;
        
        public AirtelBillDetailsRequest() {
        }
        
        public AirtelBillDetailsRequest(string strMobileno, MSDGAPI.ServiceReference1.AuthRequestBean RequestBean) {
            this.strMobileno = strMobileno;
            this.RequestBean = RequestBean;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AirtelBillDetailsResponse", WrapperNamespace="http://gateway.mobile.eseva.com", IsWrapped=true)]
    public partial class AirtelBillDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gateway.mobile.eseva.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MSDGAPI.ServiceReference1.AirtelBillResponse @return;
        
        public AirtelBillDetailsResponse() {
        }
        
        public AirtelBillDetailsResponse(MSDGAPI.ServiceReference1.AirtelBillResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IdeaBillDetails", WrapperNamespace="http://gateway.mobile.eseva.com", IsWrapped=true)]
    public partial class IdeaBillDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gateway.mobile.eseva.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string strMobileno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gateway.mobile.eseva.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MSDGAPI.ServiceReference1.AuthRequestBean RequestBean;
        
        public IdeaBillDetailsRequest() {
        }
        
        public IdeaBillDetailsRequest(string strMobileno, MSDGAPI.ServiceReference1.AuthRequestBean RequestBean) {
            this.strMobileno = strMobileno;
            this.RequestBean = RequestBean;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IdeaBillDetailsResponse", WrapperNamespace="http://gateway.mobile.eseva.com", IsWrapped=true)]
    public partial class IdeaBillDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gateway.mobile.eseva.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MSDGAPI.ServiceReference1.IdeaBillResponse @return;
        
        public IdeaBillDetailsResponse() {
        }
        
        public IdeaBillDetailsResponse(MSDGAPI.ServiceReference1.IdeaBillResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AirtelLandLineBillDetails", WrapperNamespace="http://gateway.mobile.eseva.com", IsWrapped=true)]
    public partial class AirtelLandLineBillDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gateway.mobile.eseva.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string strMobileno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gateway.mobile.eseva.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MSDGAPI.ServiceReference1.AuthRequestBean RequestBean;
        
        public AirtelLandLineBillDetailsRequest() {
        }
        
        public AirtelLandLineBillDetailsRequest(string strMobileno, MSDGAPI.ServiceReference1.AuthRequestBean RequestBean) {
            this.strMobileno = strMobileno;
            this.RequestBean = RequestBean;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AirtelLandLineBillDetailsResponse", WrapperNamespace="http://gateway.mobile.eseva.com", IsWrapped=true)]
    public partial class AirtelLandLineBillDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gateway.mobile.eseva.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MSDGAPI.ServiceReference1.AirtelLandLineBillResponse @return;
        
        public AirtelLandLineBillDetailsResponse() {
        }
        
        public AirtelLandLineBillDetailsResponse(MSDGAPI.ServiceReference1.AirtelLandLineBillResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TsmobileapssPortTypeChannel : MSDGAPI.ServiceReference1.TsmobileapssPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TsmobileapssPortTypeClient : System.ServiceModel.ClientBase<MSDGAPI.ServiceReference1.TsmobileapssPortType>, MSDGAPI.ServiceReference1.TsmobileapssPortType {
        
        public TsmobileapssPortTypeClient() {
        }
        
        public TsmobileapssPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TsmobileapssPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TsmobileapssPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TsmobileapssPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSDGAPI.ServiceReference1.HmwssbBillDetailsResponse MSDGAPI.ServiceReference1.TsmobileapssPortType.HmwssbBillDetails(MSDGAPI.ServiceReference1.HmwssbBillDetailsRequest request) {
            return base.Channel.HmwssbBillDetails(request);
        }
        
        public MSDGAPI.ServiceReference1.HmwssbBillResponse HmwssbBillDetails(string strConsno, MSDGAPI.ServiceReference1.AuthRequestBean RequestBean) {
            MSDGAPI.ServiceReference1.HmwssbBillDetailsRequest inValue = new MSDGAPI.ServiceReference1.HmwssbBillDetailsRequest();
            inValue.strConsno = strConsno;
            inValue.RequestBean = RequestBean;
            MSDGAPI.ServiceReference1.HmwssbBillDetailsResponse retVal = ((MSDGAPI.ServiceReference1.TsmobileapssPortType)(this)).HmwssbBillDetails(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSDGAPI.ServiceReference1.AirtelBillDetailsResponse MSDGAPI.ServiceReference1.TsmobileapssPortType.AirtelBillDetails(MSDGAPI.ServiceReference1.AirtelBillDetailsRequest request) {
            return base.Channel.AirtelBillDetails(request);
        }
        
        public MSDGAPI.ServiceReference1.AirtelBillResponse AirtelBillDetails(string strMobileno, MSDGAPI.ServiceReference1.AuthRequestBean RequestBean) {
            MSDGAPI.ServiceReference1.AirtelBillDetailsRequest inValue = new MSDGAPI.ServiceReference1.AirtelBillDetailsRequest();
            inValue.strMobileno = strMobileno;
            inValue.RequestBean = RequestBean;
            MSDGAPI.ServiceReference1.AirtelBillDetailsResponse retVal = ((MSDGAPI.ServiceReference1.TsmobileapssPortType)(this)).AirtelBillDetails(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSDGAPI.ServiceReference1.IdeaBillDetailsResponse MSDGAPI.ServiceReference1.TsmobileapssPortType.IdeaBillDetails(MSDGAPI.ServiceReference1.IdeaBillDetailsRequest request) {
            return base.Channel.IdeaBillDetails(request);
        }
        
        public MSDGAPI.ServiceReference1.IdeaBillResponse IdeaBillDetails(string strMobileno, MSDGAPI.ServiceReference1.AuthRequestBean RequestBean) {
            MSDGAPI.ServiceReference1.IdeaBillDetailsRequest inValue = new MSDGAPI.ServiceReference1.IdeaBillDetailsRequest();
            inValue.strMobileno = strMobileno;
            inValue.RequestBean = RequestBean;
            MSDGAPI.ServiceReference1.IdeaBillDetailsResponse retVal = ((MSDGAPI.ServiceReference1.TsmobileapssPortType)(this)).IdeaBillDetails(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSDGAPI.ServiceReference1.AirtelLandLineBillDetailsResponse MSDGAPI.ServiceReference1.TsmobileapssPortType.AirtelLandLineBillDetails(MSDGAPI.ServiceReference1.AirtelLandLineBillDetailsRequest request) {
            return base.Channel.AirtelLandLineBillDetails(request);
        }
        
        public MSDGAPI.ServiceReference1.AirtelLandLineBillResponse AirtelLandLineBillDetails(string strMobileno, MSDGAPI.ServiceReference1.AuthRequestBean RequestBean) {
            MSDGAPI.ServiceReference1.AirtelLandLineBillDetailsRequest inValue = new MSDGAPI.ServiceReference1.AirtelLandLineBillDetailsRequest();
            inValue.strMobileno = strMobileno;
            inValue.RequestBean = RequestBean;
            MSDGAPI.ServiceReference1.AirtelLandLineBillDetailsResponse retVal = ((MSDGAPI.ServiceReference1.TsmobileapssPortType)(this)).AirtelLandLineBillDetails(inValue);
            return retVal.@return;
        }
    }
}
