//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using System.Configuration;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "TsmobileapssSoap11Binding", Namespace = "http://gateway.mobile.eseva.com")]
public partial class Tsmobileapss : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback HmwssbBillDetailsOperationCompleted;

    private System.Threading.SendOrPostCallback AirtelBillDetailsOperationCompleted;

    private System.Threading.SendOrPostCallback IdeaBillDetailsOperationCompleted;

    private System.Threading.SendOrPostCallback AirtelLandLineBillDetailsOperationCompleted;

    /// <remarks/>
    public Tsmobileapss()
    {
        string URL = ConfigurationManager.AppSettings["ESEVA_MOB_SERVICE_URL"] ?? "";
        if (!string.IsNullOrEmpty(URL))
        {
            this.Url = URL;
        }
        else
        {
            this.Url = "http://eseva.telangana.gov.in/CentralPortal/services/Tsmobileapss.TsmobileapssHttpSoap11En" +
                "dpoint/";
        }
    }

    /// <remarks/>
    public event HmwssbBillDetailsCompletedEventHandler HmwssbBillDetailsCompleted;

    /// <remarks/>
    public event AirtelBillDetailsCompletedEventHandler AirtelBillDetailsCompleted;

    /// <remarks/>
    public event IdeaBillDetailsCompletedEventHandler IdeaBillDetailsCompleted;

    /// <remarks/>
    public event AirtelLandLineBillDetailsCompletedEventHandler AirtelLandLineBillDetailsCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:HmwssbBillDetails", RequestNamespace = "http://gateway.mobile.eseva.com", ResponseNamespace = "http://gateway.mobile.eseva.com", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable = true)]
    public HmwssbBillResponse HmwssbBillDetails([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string strConsno, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] AuthRequestBean RequestBean)
    {
        object[] results = this.Invoke("HmwssbBillDetails", new object[] {
                    strConsno,
                    RequestBean});
        return ((HmwssbBillResponse)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginHmwssbBillDetails(string strConsno, AuthRequestBean RequestBean, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("HmwssbBillDetails", new object[] {
                    strConsno,
                    RequestBean}, callback, asyncState);
    }

    /// <remarks/>
    public HmwssbBillResponse EndHmwssbBillDetails(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((HmwssbBillResponse)(results[0]));
    }

    /// <remarks/>
    public void HmwssbBillDetailsAsync(string strConsno, AuthRequestBean RequestBean)
    {
        this.HmwssbBillDetailsAsync(strConsno, RequestBean, null);
    }

    /// <remarks/>
    public void HmwssbBillDetailsAsync(string strConsno, AuthRequestBean RequestBean, object userState)
    {
        if ((this.HmwssbBillDetailsOperationCompleted == null))
        {
            this.HmwssbBillDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHmwssbBillDetailsOperationCompleted);
        }
        this.InvokeAsync("HmwssbBillDetails", new object[] {
                    strConsno,
                    RequestBean}, this.HmwssbBillDetailsOperationCompleted, userState);
    }

    private void OnHmwssbBillDetailsOperationCompleted(object arg)
    {
        if ((this.HmwssbBillDetailsCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.HmwssbBillDetailsCompleted(this, new HmwssbBillDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:AirtelBillDetails", RequestNamespace = "http://gateway.mobile.eseva.com", ResponseNamespace = "http://gateway.mobile.eseva.com", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable = true)]
    public AirtelBillResponse AirtelBillDetails([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string strMobileno, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] AuthRequestBean RequestBean)
    {
        object[] results = this.Invoke("AirtelBillDetails", new object[] {
                    strMobileno,
                    RequestBean});
        return ((AirtelBillResponse)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginAirtelBillDetails(string strMobileno, AuthRequestBean RequestBean, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("AirtelBillDetails", new object[] {
                    strMobileno,
                    RequestBean}, callback, asyncState);
    }

    /// <remarks/>
    public AirtelBillResponse EndAirtelBillDetails(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((AirtelBillResponse)(results[0]));
    }

    /// <remarks/>
    public void AirtelBillDetailsAsync(string strMobileno, AuthRequestBean RequestBean)
    {
        this.AirtelBillDetailsAsync(strMobileno, RequestBean, null);
    }

    /// <remarks/>
    public void AirtelBillDetailsAsync(string strMobileno, AuthRequestBean RequestBean, object userState)
    {
        if ((this.AirtelBillDetailsOperationCompleted == null))
        {
            this.AirtelBillDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAirtelBillDetailsOperationCompleted);
        }
        this.InvokeAsync("AirtelBillDetails", new object[] {
                    strMobileno,
                    RequestBean}, this.AirtelBillDetailsOperationCompleted, userState);
    }

    private void OnAirtelBillDetailsOperationCompleted(object arg)
    {
        if ((this.AirtelBillDetailsCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AirtelBillDetailsCompleted(this, new AirtelBillDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:IdeaBillDetails", RequestNamespace = "http://gateway.mobile.eseva.com", ResponseNamespace = "http://gateway.mobile.eseva.com", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable = true)]
    public IdeaBillResponse IdeaBillDetails([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string strMobileno, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] AuthRequestBean RequestBean)
    {
        object[] results = this.Invoke("IdeaBillDetails", new object[] {
                    strMobileno,
                    RequestBean});
        return ((IdeaBillResponse)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginIdeaBillDetails(string strMobileno, AuthRequestBean RequestBean, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("IdeaBillDetails", new object[] {
                    strMobileno,
                    RequestBean}, callback, asyncState);
    }

    /// <remarks/>
    public IdeaBillResponse EndIdeaBillDetails(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((IdeaBillResponse)(results[0]));
    }

    /// <remarks/>
    public void IdeaBillDetailsAsync(string strMobileno, AuthRequestBean RequestBean)
    {
        this.IdeaBillDetailsAsync(strMobileno, RequestBean, null);
    }

    /// <remarks/>
    public void IdeaBillDetailsAsync(string strMobileno, AuthRequestBean RequestBean, object userState)
    {
        if ((this.IdeaBillDetailsOperationCompleted == null))
        {
            this.IdeaBillDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIdeaBillDetailsOperationCompleted);
        }
        this.InvokeAsync("IdeaBillDetails", new object[] {
                    strMobileno,
                    RequestBean}, this.IdeaBillDetailsOperationCompleted, userState);
    }

    private void OnIdeaBillDetailsOperationCompleted(object arg)
    {
        if ((this.IdeaBillDetailsCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.IdeaBillDetailsCompleted(this, new IdeaBillDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:AirtelLandLineBillDetails", RequestNamespace = "http://gateway.mobile.eseva.com", ResponseNamespace = "http://gateway.mobile.eseva.com", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable = true)]
    public AirtelLandLineBillResponse AirtelLandLineBillDetails([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string strMobileno, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] AuthRequestBean RequestBean)
    {
        object[] results = this.Invoke("AirtelLandLineBillDetails", new object[] {
                    strMobileno,
                    RequestBean});
        return ((AirtelLandLineBillResponse)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginAirtelLandLineBillDetails(string strMobileno, AuthRequestBean RequestBean, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("AirtelLandLineBillDetails", new object[] {
                    strMobileno,
                    RequestBean}, callback, asyncState);
    }

    /// <remarks/>
    public AirtelLandLineBillResponse EndAirtelLandLineBillDetails(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((AirtelLandLineBillResponse)(results[0]));
    }

    /// <remarks/>
    public void AirtelLandLineBillDetailsAsync(string strMobileno, AuthRequestBean RequestBean)
    {
        this.AirtelLandLineBillDetailsAsync(strMobileno, RequestBean, null);
    }

    /// <remarks/>
    public void AirtelLandLineBillDetailsAsync(string strMobileno, AuthRequestBean RequestBean, object userState)
    {
        if ((this.AirtelLandLineBillDetailsOperationCompleted == null))
        {
            this.AirtelLandLineBillDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAirtelLandLineBillDetailsOperationCompleted);
        }
        this.InvokeAsync("AirtelLandLineBillDetails", new object[] {
                    strMobileno,
                    RequestBean}, this.AirtelLandLineBillDetailsOperationCompleted, userState);
    }

    private void OnAirtelLandLineBillDetailsOperationCompleted(object arg)
    {
        if ((this.AirtelLandLineBillDetailsCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AirtelLandLineBillDetailsCompleted(this, new AirtelLandLineBillDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://auth.gateway.mobile.eseva.com/xsd")]
public partial class AuthRequestBean
{

    private string groupidField;

    private string passwordField;

    private string serviceidField;

    private string strCentrecodeField;

    private string strDistcodeField;

    private string strStaffcodeField;

    private string strdeptcodeField;

    private string userIdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string groupid
    {
        get
        {
            return this.groupidField;
        }
        set
        {
            this.groupidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string serviceid
    {
        get
        {
            return this.serviceidField;
        }
        set
        {
            this.serviceidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strCentrecode
    {
        get
        {
            return this.strCentrecodeField;
        }
        set
        {
            this.strCentrecodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strDistcode
    {
        get
        {
            return this.strDistcodeField;
        }
        set
        {
            this.strDistcodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strStaffcode
    {
        get
        {
            return this.strStaffcodeField;
        }
        set
        {
            this.strStaffcodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strdeptcode
    {
        get
        {
            return this.strdeptcodeField;
        }
        set
        {
            this.strdeptcodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string userId
    {
        get
        {
            return this.userIdField;
        }
        set
        {
            this.userIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://airtelLandLine.gateway.mobile.eseva.com/xsd")]
public partial class AirtelLandLineBillResponse
{

    private string strAccountnoField;

    private string strBillamountField;

    private string strConsumernameField;

    private string strReqidField;

    private string strResCodeField;

    private string strResDescField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strAccountno
    {
        get
        {
            return this.strAccountnoField;
        }
        set
        {
            this.strAccountnoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strBillamount
    {
        get
        {
            return this.strBillamountField;
        }
        set
        {
            this.strBillamountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strConsumername
    {
        get
        {
            return this.strConsumernameField;
        }
        set
        {
            this.strConsumernameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strReqid
    {
        get
        {
            return this.strReqidField;
        }
        set
        {
            this.strReqidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strResCode
    {
        get
        {
            return this.strResCodeField;
        }
        set
        {
            this.strResCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strResDesc
    {
        get
        {
            return this.strResDescField;
        }
        set
        {
            this.strResDescField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://idea.gateway.mobile.eseva.com/xsd")]
public partial class IdeaBillResponse
{

    private string strAccountnoField;

    private string strAdd1Field;

    private string strAdd2Field;

    private string strAdd3Field;

    private string strBillamountField;

    private string strConsumernameField;

    private string strReqidField;

    private string strResCodeField;

    private string strResDescField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strAccountno
    {
        get
        {
            return this.strAccountnoField;
        }
        set
        {
            this.strAccountnoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strAdd1
    {
        get
        {
            return this.strAdd1Field;
        }
        set
        {
            this.strAdd1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strAdd2
    {
        get
        {
            return this.strAdd2Field;
        }
        set
        {
            this.strAdd2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strAdd3
    {
        get
        {
            return this.strAdd3Field;
        }
        set
        {
            this.strAdd3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strBillamount
    {
        get
        {
            return this.strBillamountField;
        }
        set
        {
            this.strBillamountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strConsumername
    {
        get
        {
            return this.strConsumernameField;
        }
        set
        {
            this.strConsumernameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strReqid
    {
        get
        {
            return this.strReqidField;
        }
        set
        {
            this.strReqidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strResCode
    {
        get
        {
            return this.strResCodeField;
        }
        set
        {
            this.strResCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strResDesc
    {
        get
        {
            return this.strResDescField;
        }
        set
        {
            this.strResDescField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://airtel.gateway.mobile.eseva.com/xsd")]
public partial class AirtelBillResponse
{

    private string strAccountnoField;

    private string strBillamountField;

    private string strConsumernameField;

    private string strReqidField;

    private string strResCodeField;

    private string strResDescField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strAccountno
    {
        get
        {
            return this.strAccountnoField;
        }
        set
        {
            this.strAccountnoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strBillamount
    {
        get
        {
            return this.strBillamountField;
        }
        set
        {
            this.strBillamountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strConsumername
    {
        get
        {
            return this.strConsumernameField;
        }
        set
        {
            this.strConsumernameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strReqid
    {
        get
        {
            return this.strReqidField;
        }
        set
        {
            this.strReqidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strResCode
    {
        get
        {
            return this.strResCodeField;
        }
        set
        {
            this.strResCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strResDesc
    {
        get
        {
            return this.strResDescField;
        }
        set
        {
            this.strResDescField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hmwssb.gateway.mobile.eseva.com/xsd")]
public partial class HmwssbBillResponse
{

    private string strAddressField;

    private string strAmountField;

    private string strCanField;

    private string strCategoryField;

    private string strEmailField;

    private string strMobilenoField;

    private string strNameField;

    private string strReqIdField;

    private string strResCodeField;

    private string strResDescField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strAddress
    {
        get
        {
            return this.strAddressField;
        }
        set
        {
            this.strAddressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strAmount
    {
        get
        {
            return this.strAmountField;
        }
        set
        {
            this.strAmountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strCan
    {
        get
        {
            return this.strCanField;
        }
        set
        {
            this.strCanField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strCategory
    {
        get
        {
            return this.strCategoryField;
        }
        set
        {
            this.strCategoryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strEmail
    {
        get
        {
            return this.strEmailField;
        }
        set
        {
            this.strEmailField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strMobileno
    {
        get
        {
            return this.strMobilenoField;
        }
        set
        {
            this.strMobilenoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strName
    {
        get
        {
            return this.strNameField;
        }
        set
        {
            this.strNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strReqId
    {
        get
        {
            return this.strReqIdField;
        }
        set
        {
            this.strReqIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strResCode
    {
        get
        {
            return this.strResCodeField;
        }
        set
        {
            this.strResCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string strResDesc
    {
        get
        {
            return this.strResDescField;
        }
        set
        {
            this.strResDescField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void HmwssbBillDetailsCompletedEventHandler(object sender, HmwssbBillDetailsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HmwssbBillDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal HmwssbBillDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public HmwssbBillResponse Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((HmwssbBillResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void AirtelBillDetailsCompletedEventHandler(object sender, AirtelBillDetailsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AirtelBillDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal AirtelBillDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public AirtelBillResponse Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((AirtelBillResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void IdeaBillDetailsCompletedEventHandler(object sender, IdeaBillDetailsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class IdeaBillDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal IdeaBillDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public IdeaBillResponse Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((IdeaBillResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void AirtelLandLineBillDetailsCompletedEventHandler(object sender, AirtelLandLineBillDetailsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AirtelLandLineBillDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal AirtelLandLineBillDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public AirtelLandLineBillResponse Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((AirtelLandLineBillResponse)(this.results[0]));
        }
    }
}
